function Hd = filter1M_start100k_stop115k
%FILTER1M_START100K_STOP115K 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 18-Dec-2020 15:59:26

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 1000;  % Sampling Frequency

Fpass = 100;             % Passband Frequency
Fstop = 115;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
