function Hd = filter200_325_start100k_stop101
%FILTER200_325_START100K_STOP101 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 21-Dec-2020 11:27:20

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 203.125;  % Sampling Frequency

Fpass = 100;              % Passband Frequency
Fstop = 101;              % Stopband Frequency
Dpass = 0.057501127785;   % Passband Ripple
Dstop = 0.0031622776602;  % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
