function Hd = filter_65M_70_6_5m
%FILTER_65M_70_6_5M 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 02-Dec-2020 20:07:30

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 65;  % Sampling Frequency

Fpass = 15.03678;          % Passband Frequency
Fstop = 18.34473;          % Stopband Frequency
Dpass = 0.057501127785;    % Passband Ripple
Dstop = 0.00031622776602;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
